[package]
name = "z3"
version = "0.3.2"
authors = ["Graydon Hoare <graydon@pobox.com>", "Bruce Mitchener <bruce.mitchener@gmail.com>"]

description = "High-level rust bindings for the Z3 SMT solver from Microsoft Research"
license = "MIT"
keywords = ["FFI", "SMT", "satisfiability", "solver"]
categories = ["api-bindings"]
readme = "README.md"
documentation = "https://docs.rs/z3/"
homepage = "https://github.com/prove-rs/z3.rs"
repository = "https://github.com/prove-rs/z3.rs.git"

[dependencies]
log = "0.4"

[dev-dependencies]
env_logger = "0.6"
semver = "0.9"

[dependencies.z3-sys]
path = "../z3-sys"
version = "0.4.0"
